project:
  type: website
  output-dir: docs  # <-- add this

website:
  title: "quarto-website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: posts.qmd
        text: Post
      - href: projects.qmd
        text: Projects
      - text: Presentation
        href: presentation/Luo_Runyu-kmedoids_customer_segmentation.qmd
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
